### ISSUE TITLE
Resource Route Attribute

### ISSUE THREAD

**Issue by TheCadien** [FriendsOfSulu/SuluAttributesBundle#1]
The routes for a resource route are currently configured via `sulu_admin.yml`
There will also be a dual attribute for this in the future. 

Current Exmaple configuration
```
    resources:
        events:
            routes:
                list: app.get_event_list
                detail: app.get_event
```

Possible realisation.
